// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "EvelyApi": pins Resource Client
//
// Command:
// $ goagen
// --design=EvelyApi/design
// --out=$(GOPATH)/src/EvelyApi
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// OffPinsPath computes a request path to the off action of pins.
func OffPinsPath() string {

	return fmt.Sprintf("/api/develop/v2/pins/off")
}

// ピンを外す
func (c *Client) OffPins(ctx context.Context, path string, payload *PinPayload, contentType string) (*http.Response, error) {
	req, err := c.NewOffPinsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewOffPinsRequest create the request corresponding to the off action endpoint of the pins resource.
func (c *Client) NewOffPinsRequest(ctx context.Context, path string, payload *PinPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// OnPinsPath computes a request path to the on action of pins.
func OnPinsPath() string {

	return fmt.Sprintf("/api/develop/v2/pins/on")
}

// ピンする
func (c *Client) OnPins(ctx context.Context, path string, payload *PinPayload, contentType string) (*http.Response, error) {
	req, err := c.NewOnPinsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewOnPinsRequest create the request corresponding to the on action endpoint of the pins resource.
func (c *Client) NewOnPinsRequest(ctx context.Context, path string, payload *PinPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
