// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "EvelyApi": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=EvelyApi/design
// --out=$(GOPATH)/src/EvelyApi
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// EventsHref returns the resource href.
func EventsHref() string {
	return "/api/develop/v2/events/detail"
}

// UsersHref returns the resource href.
func UsersHref(userID interface{}) string {
	paramuserID := strings.TrimLeftFunc(fmt.Sprintf("%v", userID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/develop/v2/users/%v", paramuserID)
}
