// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "EvelyApi": CLI Commands
//
// Command:
// $ goagen
// --design=EvelyApi/design
// --out=$(GOPATH)/src/EvelyApi
// --version=v1.3.1

package cli

import (
	"EvelyApi/client"
	"context"
	"encoding/json"
	"fmt"
	"github.com/goadesign/goa"
	goaclient "github.com/goadesign/goa/client"
	uuid "github.com/goadesign/goa/uuid"
	"github.com/spf13/cobra"
	"log"
	"net/url"
	"os"
	"path"
	"strconv"
	"strings"
	"time"
)

type (
	// SendMailAuthCommand is the command line data structure for the send_mail action of auth
	SendMailAuthCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// SigninAuthCommand is the command line data structure for the signin action of auth
	SigninAuthCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// SignupAuthCommand is the command line data structure for the signup action of auth
	SignupAuthCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// VerifyTokenAuthCommand is the command line data structure for the verify_token action of auth
	VerifyTokenAuthCommand struct {
		// トークン
		Token       string
		PrettyPrint bool
	}

	// CreateEventsCommand is the command line data structure for the create action of events
	CreateEventsCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// DeleteEventsCommand is the command line data structure for the delete action of events
	DeleteEventsCommand struct {
		// イベントID
		EventID     string
		PrettyPrint bool
	}

	// ListEventsCommand is the command line data structure for the list action of events
	ListEventsCommand struct {
		// キーワード
		Keyword string
		// 取得件数
		Limit int
		// 除外件数
		Offset      int
		PrettyPrint bool
	}

	// ModifyEventsCommand is the command line data structure for the modify action of events
	ModifyEventsCommand struct {
		Payload     string
		ContentType string
		// イベントID
		EventID     string
		PrettyPrint bool
	}

	// NearbyEventsCommand is the command line data structure for the nearby action of events
	NearbyEventsCommand struct {
		// 緯度
		Lat string
		// 取得件数
		Limit int
		// 経度
		Lng string
		// 除外件数
		Offset int
		// 検索範囲(半径m)
		Range       int
		PrettyPrint bool
	}

	// NotifyByInstanceIDEventsCommand is the command line data structure for the notify_by_instance_id action of events
	NotifyByInstanceIDEventsCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// NotifyByUserIDEventsCommand is the command line data structure for the notify_by_user_id action of events
	NotifyByUserIDEventsCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// PinEventsCommand is the command line data structure for the pin action of events
	PinEventsCommand struct {
		// ユーザーID
		UserID string
		// 取得件数
		Limit int
		// 除外件数
		Offset      int
		PrettyPrint bool
	}

	// ShowEventsCommand is the command line data structure for the show action of events
	ShowEventsCommand struct {
		// 詳細を見るイベントのID配列
		Ids         []string
		PrettyPrint bool
	}

	// UpdateEventsCommand is the command line data structure for the update action of events
	UpdateEventsCommand struct {
		PrettyPrint bool
	}

	// UploadFilesCommand is the command line data structure for the upload action of files
	UploadFilesCommand struct {
		PrettyPrint bool
	}

	// OffPinsCommand is the command line data structure for the off action of pins
	OffPinsCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// OnPinsCommand is the command line data structure for the on action of pins
	OnPinsCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// CreateReviewsCommand is the command line data structure for the create action of reviews
	CreateReviewsCommand struct {
		Payload     string
		ContentType string
		// イベントID
		EventID     string
		PrettyPrint bool
	}

	// ListReviewsCommand is the command line data structure for the list action of reviews
	ListReviewsCommand struct {
		// イベントID
		EventID string
		// 取得件数
		Limit int
		// 除外件数
		Offset      int
		PrettyPrint bool
	}

	// ShowUsersCommand is the command line data structure for the show action of users
	ShowUsersCommand struct {
		// ユーザーID
		UserID      string
		PrettyPrint bool
	}

	// DownloadCommand is the command line data structure for the download command.
	DownloadCommand struct {
		// OutFile is the path to the download output file.
		OutFile string
	}
)

// RegisterCommands registers the resource action CLI commands.
func RegisterCommands(app *cobra.Command, c *client.Client) {
	var command, sub *cobra.Command
	command = &cobra.Command{
		Use:   "create",
		Short: `create action`,
	}
	tmp1 := new(CreateEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events"]`,
		Short: ``,
		Long: `

Payload example:

{
   "body": "初心者でもGitを扱えるようになる勉強会を開催します！\nノートPCを各自持参してください。",
   "mail": "yKicchanApp@gmail.com",
   "noticeRange": 500,
   "openFlg": false,
   "plans": [
      {
         "location": {
            "lat": 34.706424,
            "lng": 135.50123,
            "name": "ECCコンピュータ専門学校2303教室"
         },
         "upcomingDate": {
            "endDate": "1990-02-18T14:03:59Z",
            "startDate": "1975-07-28T07:45:40Z"
         }
      },
      {
         "location": {
            "lat": 34.706424,
            "lng": 135.50123,
            "name": "ECCコンピュータ専門学校2303教室"
         },
         "upcomingDate": {
            "endDate": "1990-02-18T14:03:59Z",
            "startDate": "1975-07-28T07:45:40Z"
         }
      },
      {
         "location": {
            "lat": 34.706424,
            "lng": 135.50123,
            "name": "ECCコンピュータ専門学校2303教室"
         },
         "upcomingDate": {
            "endDate": "1990-02-18T14:03:59Z",
            "startDate": "1975-07-28T07:45:40Z"
         }
      }
   ],
   "scope": "public",
   "tel": "090-1234-5678",
   "title": "Git勉強会",
   "url": "http://comp.ecc.ac.jp/"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp1.Run(c, args) },
	}
	tmp1.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp1.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	tmp2 := new(CreateReviewsCommand)
	sub = &cobra.Command{
		Use:   `reviews ["/api/develop/v2/reviews/EVENT_ID"]`,
		Short: ``,
		Long: `

Payload example:

{
   "body": "yym",
   "rate": 4,
   "title": "ygva5jk"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp2.Run(c, args) },
	}
	tmp2.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp2.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "delete",
		Short: `イベント削除`,
	}
	tmp3 := new(DeleteEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/EVENT_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp3.Run(c, args) },
	}
	tmp3.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp3.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list",
		Short: `list action`,
	}
	tmp4 := new(ListEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp4.Run(c, args) },
	}
	tmp4.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp4.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	tmp5 := new(ListReviewsCommand)
	sub = &cobra.Command{
		Use:   `reviews ["/api/develop/v2/reviews/EVENT_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp5.Run(c, args) },
	}
	tmp5.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp5.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "modify",
		Short: `イベント編集`,
	}
	tmp6 := new(ModifyEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/EVENT_ID"]`,
		Short: ``,
		Long: `

Payload example:

{
   "body": "初心者でもGitを扱えるようになる勉強会を開催します！\nノートPCを各自持参してください。",
   "mail": "yKicchanApp@gmail.com",
   "noticeRange": 500,
   "openFlg": false,
   "plans": [
      {
         "location": {
            "lat": 34.706424,
            "lng": 135.50123,
            "name": "ECCコンピュータ専門学校2303教室"
         },
         "upcomingDate": {
            "endDate": "1990-02-18T14:03:59Z",
            "startDate": "1975-07-28T07:45:40Z"
         }
      },
      {
         "location": {
            "lat": 34.706424,
            "lng": 135.50123,
            "name": "ECCコンピュータ専門学校2303教室"
         },
         "upcomingDate": {
            "endDate": "1990-02-18T14:03:59Z",
            "startDate": "1975-07-28T07:45:40Z"
         }
      },
      {
         "location": {
            "lat": 34.706424,
            "lng": 135.50123,
            "name": "ECCコンピュータ専門学校2303教室"
         },
         "upcomingDate": {
            "endDate": "1990-02-18T14:03:59Z",
            "startDate": "1975-07-28T07:45:40Z"
         }
      }
   ],
   "scope": "public",
   "tel": "090-1234-5678",
   "title": "Git勉強会",
   "url": "http://comp.ecc.ac.jp/"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp6.Run(c, args) },
	}
	tmp6.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp6.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "nearby",
		Short: `近くのイベントを検索する`,
	}
	tmp7 := new(NearbyEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/nearby"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp7.Run(c, args) },
	}
	tmp7.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp7.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "notify-by-instanceid",
		Short: `近くにイベントがあればインスタンスID宛に通知する`,
	}
	tmp6 := new(NotifyByInstanceIDEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/notify/by_instance_id"]`,
		Short: ``,
		Long: `

Payload example:

{
   "instanceID": "token",
   "lat": 34.706424,
   "lng": 135.50123
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp8.Run(c, args) },
	}
	tmp8.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp8.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "notify-by-userid",
		Short: `近くにイベントがあればユーザーのデバイス全てに通知する`,
	}
	tmp7 := new(NotifyByUserIDEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/notify/by_user_id"]`,
		Short: ``,
		Long: `

Payload example:

{
   "lat": 34.706424,
   "lng": 135.50123
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp7.Run(c, args) },
	}
	tmp7.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp7.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "off",
		Short: `ピンを外す`,
	}
	tmp8 := new(OffPinsCommand)
	sub = &cobra.Command{
		Use:   `pins ["/api/develop/v2/pins/off"]`,
		Short: ``,
		Long: `

Payload example:

{
   "ids": [
      "5a44d5f2775672b659ba00fa",
      "5a44d5f2775672b659ba00fb"
   ]
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp8.Run(c, args) },
	}
	tmp8.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp8.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "on",
		Short: `ピンする`,
	}
	tmp9 := new(OnPinsCommand)
	sub = &cobra.Command{
		Use:   `pins ["/api/develop/v2/pins/on"]`,
		Short: ``,
		Long: `

Payload example:

{
   "ids": [
      "5a44d5f2775672b659ba00fa",
      "5a44d5f2775672b659ba00fb"
   ]
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp9.Run(c, args) },
	}
	tmp9.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp9.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "pin",
		Short: `ユーザーのピンしたイベント一覧を取得する`,
	}
	tmp10 := new(PinEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/pin/USER_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp10.Run(c, args) },
	}
	tmp10.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp10.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "send-mail",
		Short: `新規登録用のメール送信`,
	}
	tmp11 := new(SendMailAuthCommand)
	sub = &cobra.Command{
		Use:   `auth ["/api/develop/v2/auth/signup/send_mail"]`,
		Short: ``,
		Long: `

Payload example:

{
   "email": "yKicchanApp@gmail.com"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp11.Run(c, args) },
	}
	tmp11.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp11.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show",
		Short: `show action`,
	}
	tmp12 := new(ShowEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/detail"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp12.Run(c, args) },
	}
	tmp12.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp12.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	tmp13 := new(ShowUsersCommand)
	sub = &cobra.Command{
		Use:   `users ["/api/develop/v2/users/USER_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp13.Run(c, args) },
	}
	tmp13.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp13.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "signin",
		Short: `ログイン`,
	}
	tmp14 := new(SigninAuthCommand)
	sub = &cobra.Command{
		Use:   `auth ["/api/develop/v2/auth/signin"]`,
		Short: ``,
		Long: `

Payload example:

{
   "id": "yKicchan",
   "password": "password"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp14.Run(c, args) },
	}
	tmp14.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp14.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "signup",
		Short: `新規登録`,
	}
	tmp15 := new(SignupAuthCommand)
	sub = &cobra.Command{
		Use:   `auth ["/api/develop/v2/auth/signup"]`,
		Short: ``,
		Long: `

Payload example:

{
   "InstanceID": "token",
   "id": "yKicchan",
   "mail": "yKicchanApp@gmail.com",
   "name": "きっちゃそ",
   "password": "password",
   "tel": "090-1234-5678"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp15.Run(c, args) },
	}
	tmp15.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp15.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "update",
		Short: `イベントの開催フラグを更新する`,
	}
	tmp16 := new(UpdateEventsCommand)
	sub = &cobra.Command{
		Use:   `events ["/api/develop/v2/events/update"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp16.Run(c, args) },
	}
	tmp16.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp16.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "upload",
		Short: `ファイルアップロード`,
	}
	tmp17 := new(UploadFilesCommand)
	sub = &cobra.Command{
		Use:   `files ["/api/develop/v2/files/upload"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp17.Run(c, args) },
	}
	tmp17.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp17.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "verify-token",
		Short: `新規登録時のトークンのチェック`,
	}
	tmp18 := new(VerifyTokenAuthCommand)
	sub = &cobra.Command{
		Use:   `auth ["/api/develop/v2/auth/signup/verify_token"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp18.Run(c, args) },
	}
	tmp18.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp18.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)

	dl := new(DownloadCommand)
	dlc := &cobra.Command{
		Use:   "download [PATH]",
		Short: "Download file with given path",
		RunE: func(cmd *cobra.Command, args []string) error {
			return dl.Run(c, args)
		},
	}
	dlc.Flags().StringVar(&dl.OutFile, "out", "", "Output file")
	app.AddCommand(dlc)
}

func intFlagVal(name string, parsed int) *int {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func float64FlagVal(name string, parsed float64) *float64 {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func boolFlagVal(name string, parsed bool) *bool {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func stringFlagVal(name string, parsed string) *string {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func hasFlag(name string) bool {
	for _, arg := range os.Args[1:] {
		if strings.HasPrefix(arg, "--"+name) {
			return true
		}
	}
	return false
}

func jsonVal(val string) (*interface{}, error) {
	var t interface{}
	err := json.Unmarshal([]byte(val), &t)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func jsonArray(ins []string) ([]interface{}, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []interface{}
	for _, id := range ins {
		val, err := jsonVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, val)
	}
	return vals, nil
}

func timeVal(val string) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339, val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func timeArray(ins []string) ([]time.Time, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []time.Time
	for _, id := range ins {
		val, err := timeVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func uuidVal(val string) (*uuid.UUID, error) {
	t, err := uuid.FromString(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func uuidArray(ins []string) ([]uuid.UUID, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []uuid.UUID
	for _, id := range ins {
		val, err := uuidVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func float64Val(val string) (*float64, error) {
	t, err := strconv.ParseFloat(val, 64)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func float64Array(ins []string) ([]float64, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []float64
	for _, id := range ins {
		val, err := float64Val(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func boolVal(val string) (*bool, error) {
	t, err := strconv.ParseBool(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func boolArray(ins []string) ([]bool, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []bool
	for _, id := range ins {
		val, err := boolVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

// Run downloads files with given paths.
func (cmd *DownloadCommand) Run(c *client.Client, args []string) error {
	var (
		fnf func(context.Context, string) (int64, error)
		fnd func(context.Context, string, string) (int64, error)

		rpath   = args[0]
		outfile = cmd.OutFile
		logger  = goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
		ctx     = goa.WithLogger(context.Background(), logger)
		err     error
	)

	if rpath[0] != '/' {
		rpath = "/" + rpath
	}
	if rpath == "/swagger.json" {
		fnf = c.DownloadSwaggerJSON
		if outfile == "" {
			outfile = "swagger.json"
		}
		goto found
	}
	if strings.HasPrefix(rpath, "/files/") {
		fnd = c.DownloadFiles
		rpath = rpath[7:]
		if outfile == "" {
			_, outfile = path.Split(rpath)
		}
		goto found
	}
	if strings.HasPrefix(rpath, "/swaggerui/") {
		fnd = c.DownloadSwaggerui
		rpath = rpath[11:]
		if outfile == "" {
			_, outfile = path.Split(rpath)
		}
		goto found
	}
	return fmt.Errorf("don't know how to download %s", rpath)
found:
	ctx = goa.WithLogContext(ctx, "file", outfile)
	if fnf != nil {
		_, err = fnf(ctx, outfile)
	} else {
		_, err = fnd(ctx, rpath, outfile)
	}
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	return nil
}

// Run makes the HTTP request corresponding to the SendMailAuthCommand command.
func (cmd *SendMailAuthCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/auth/signup/send_mail"
	}
	var payload client.SignupPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.SendMailAuth(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SendMailAuthCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the SigninAuthCommand command.
func (cmd *SigninAuthCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/auth/signin"
	}
	var payload client.LoginPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.SigninAuth(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SigninAuthCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the SignupAuthCommand command.
func (cmd *SignupAuthCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/auth/signup"
	}
	var payload client.UserPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.SignupAuth(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SignupAuthCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the VerifyTokenAuthCommand command.
func (cmd *VerifyTokenAuthCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/auth/signup/verify_token"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.VerifyTokenAuth(ctx, path, cmd.Token)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *VerifyTokenAuthCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var token string
	cc.Flags().StringVar(&cmd.Token, "token", token, `トークン`)
}

// Run makes the HTTP request corresponding to the CreateEventsCommand command.
func (cmd *CreateEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events"
	}
	var payload client.EventPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.CreateEvents(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *CreateEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the DeleteEventsCommand command.
func (cmd *DeleteEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/develop/v2/events/%v", url.QueryEscape(cmd.EventID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.DeleteEvents(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *DeleteEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var eventID string
	cc.Flags().StringVar(&cmd.EventID, "event_id", eventID, `イベントID`)
}

// Run makes the HTTP request corresponding to the ListEventsCommand command.
func (cmd *ListEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListEvents(ctx, path, stringFlagVal("keyword", cmd.Keyword), intFlagVal("limit", cmd.Limit), intFlagVal("offset", cmd.Offset))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var keyword string
	cc.Flags().StringVar(&cmd.Keyword, "keyword", keyword, `キーワード`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 10, `取得件数`)
	var offset int
	cc.Flags().IntVar(&cmd.Offset, "offset", offset, `除外件数`)
}

// Run makes the HTTP request corresponding to the ModifyEventsCommand command.
func (cmd *ModifyEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/develop/v2/events/%v", url.QueryEscape(cmd.EventID))
	}
	var payload client.EventPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ModifyEvents(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ModifyEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var eventID string
	cc.Flags().StringVar(&cmd.EventID, "event_id", eventID, `イベントID`)
}

// Run makes the HTTP request corresponding to the NearbyEventsCommand command.
func (cmd *NearbyEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events/nearby"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	var tmp19 *float64
	if cmd.Lat != "" {
		var err error
		tmp19, err = float64Val(cmd.Lat)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *float64 value", "flag", "--lat", "err", err)
			return err
		}
	}
	if tmp19 == nil {
		goa.LogError(ctx, "required flag is missing", "flag", "--lat")
		return fmt.Errorf("required flag lat is missing")
	}
	var tmp20 *float64
	if cmd.Lng != "" {
		var err error
		tmp20, err = float64Val(cmd.Lng)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *float64 value", "flag", "--lng", "err", err)
			return err
		}
	}
	if tmp20 == nil {
		goa.LogError(ctx, "required flag is missing", "flag", "--lng")
		return fmt.Errorf("required flag lng is missing")
	}
	resp, err := c.NearbyEvents(ctx, path, *tmp19, *tmp20, cmd.Range, intFlagVal("limit", cmd.Limit), intFlagVal("offset", cmd.Offset))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *NearbyEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var lat string
	cc.Flags().StringVar(&cmd.Lat, "lat", lat, `緯度`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 3, `取得件数`)
	var lng string
	cc.Flags().StringVar(&cmd.Lng, "lng", lng, `経度`)
	var offset int
	cc.Flags().IntVar(&cmd.Offset, "offset", offset, `除外件数`)
	cc.Flags().IntVar(&cmd.Range, "range", 500, `検索範囲(半径m)`)
}

// Run makes the HTTP request corresponding to the NotifyByInstanceIDEventsCommand command.
func (cmd *NotifyByInstanceIDEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events/notify/by_instance_id"
	}
	var payload client.NotifyByInstanceIDPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.NotifyByInstanceIDEvents(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *NotifyByInstanceIDEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the NotifyByUserIDEventsCommand command.
func (cmd *NotifyByUserIDEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events/notify/by_user_id"
	}
	var payload client.NotifyByUserIDPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.NotifyByUserIDEvents(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *NotifyByUserIDEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the PinEventsCommand command.
func (cmd *PinEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/develop/v2/events/pin/%v", url.QueryEscape(cmd.UserID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.PinEvents(ctx, path, intFlagVal("limit", cmd.Limit), intFlagVal("offset", cmd.Offset))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *PinEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var userID string
	cc.Flags().StringVar(&cmd.UserID, "user_id", userID, `ユーザーID`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 10, `取得件数`)
	var offset int
	cc.Flags().IntVar(&cmd.Offset, "offset", offset, `除外件数`)
}

// Run makes the HTTP request corresponding to the ShowEventsCommand command.
func (cmd *ShowEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events/detail"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowEvents(ctx, path, cmd.Ids)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var ids []string
	cc.Flags().StringSliceVar(&cmd.Ids, "ids", ids, `詳細を見るイベントのID配列`)
}

// Run makes the HTTP request corresponding to the UpdateEventsCommand command.
func (cmd *UpdateEventsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/events/update"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.UpdateEvents(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *UpdateEventsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
}

// Run makes the HTTP request corresponding to the UploadFilesCommand command.
func (cmd *UploadFilesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/files/upload"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.UploadFiles(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *UploadFilesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
}

// Run makes the HTTP request corresponding to the OffPinsCommand command.
func (cmd *OffPinsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/pins/off"
	}
	var payload client.PinPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.OffPins(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *OffPinsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the OnPinsCommand command.
func (cmd *OnPinsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/develop/v2/pins/on"
	}
	var payload client.PinPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.OnPins(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *OnPinsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the CreateReviewsCommand command.
func (cmd *CreateReviewsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/develop/v2/reviews/%v", url.QueryEscape(cmd.EventID))
	}
	var payload client.ReviewPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.CreateReviews(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *CreateReviewsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var eventID string
	cc.Flags().StringVar(&cmd.EventID, "event_id", eventID, `イベントID`)
}

// Run makes the HTTP request corresponding to the ListReviewsCommand command.
func (cmd *ListReviewsCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/develop/v2/reviews/%v", url.QueryEscape(cmd.EventID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListReviews(ctx, path, intFlagVal("limit", cmd.Limit), intFlagVal("offset", cmd.Offset))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListReviewsCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var eventID string
	cc.Flags().StringVar(&cmd.EventID, "event_id", eventID, `イベントID`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 5, `取得件数`)
	var offset int
	cc.Flags().IntVar(&cmd.Offset, "offset", offset, `除外件数`)
}

// Run makes the HTTP request corresponding to the ShowUsersCommand command.
func (cmd *ShowUsersCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/develop/v2/users/%v", url.QueryEscape(cmd.UserID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowUsers(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowUsersCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var userID string
	cc.Flags().StringVar(&cmd.UserID, "user_id", userID, `ユーザーID`)
}
