// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "EvelyApi": swagger TestHelpers
//
// Command:
// $ goagen
// --design=EvelyApi/design
// --out=$(GOPATH)/src/EvelyApi
// --version=v1.3.0

package test
